### PR TITLE
Tweak whitespace in and around text

### PR DESCRIPTION
**Pull request by Awjin**
I think these changes help make the text even more readable:

  1. Whitespace above and below the body text give proper padding from the screen's edge.

  2. Whitespace above headers gives clearer punctuation of sections

  3. Slightly decreased line-width (puts it at about 70-80 chars per line)

### CODE REVIEW

**Comment by KeenRivals** [comment]
Those margins are way too big to for mobile in my opinion. Here's a simulated Galaxy S5:

# Current Margins



# Proposed Margins

**Comment by Awjin** [comment]
imo the wide spacing reflects the content, which makes bold and emphatic points. Every heading has more impact. I see where you're coming from (the whitespace is a bit of a visual shock), but I ask that you give it five minutes to grow on you.

[This book on typography](http://practicaltypography.com/space-above-and-below.html) does a better job of explaining heading spacing.

**Comment by KeenRivals** [comment]
I was referring mostly to the x-margins. The y-margin is a little more generous than I'd like, but not so bad. There is some discussion on vertical spacing already in #21 which I'm leaning towards implementing.

**Comment by Awjin** [comment]
True, the horizontal margin could decrease. How do you feel about the added padding to the top and bottom of the page?

**Comment by KeenRivals** [comment]
> How do you feel about the added padding to the top and bottom of the page?

Not really a fan. It seems to be wasteful.

**Comment by Awjin** [comment]
I think without padding the text ends abruptly at the screen's edge, much like a book or page of text without margins. Just my opinion though

**Pull request closed without merging**
