### PR TITLE
Change position of style tags

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Put the style tag in the end. Why should the user wait for the content while the CSS loads?

### CODE REVIEW

**Comment by KeenRivals** [comment]
What is the benefit of doing this? Couldn't it result in a flash of un-styled content in *extremely* slow connections?

**Comment by FrancosLab** [comment]
Better yet, move to inline styles.

**Comment by Wolf480pl** [comment]
>Couldn't it result in a flash of un-styled content in extremely slow connections?
I think that was the point.

It's a motherfucking website.
The main purpose is the user being able to read the content.
If they have an extremely slow connection, or the connection drops after a certain point, I think it's better to show more content without style than less content but with style.

**Comment by sweepies** [comment]
You don't load an HTML file in bits, you get nothing until you have it all. It's best practice to have stylesheets in the `<head>` tag. What you're looking for is to embed them with `<link>` tags, meaning the HTML is parsed without needing to have the stylesheet loaded already.

If your connection is so slow that loading 6KB takes a long time, good luck browsing the web anyways.

**Comment by KeenRivals** [comment]
I agree that it's best practice to keep the styles in the ``<head>``. Putting ``<style>`` and ``<script>`` at the bottom of ``<body>`` has always felt like a hack for sites serving bloated styles and scripts.

**Pull request closed without merging**
