### PR TITLE
adding darkmode

### PR DESCRIPTION
**Pull request by ek926m**
I found your website and I fckn love the sarcasm in it. I added a dark mode button, maybe you like it.

### CODE REVIEW

**Comment by KeenRivals** [comment]
Uses javascript

**Comment by ek926m** [comment]
@KeenRivals  you could make another html, but you have to link it. Otherwise I have no clue to realize a dark mode

**Comment by KeenRivals** [comment]
You might be able to do it with CSS at some point in the future: https://css-tricks.com/dark-modes-with-css/

Though I'm not sure I'd merge it. The point of this site is to be brutally simplistic.

**Comment by ek926m** [comment]
@KeenRivals okay, no problem, see ya.

**Pull request closed without merging**
