### PR TITLE
Removed Bad Request

### PR DESCRIPTION
**Pull request by realabbas**
# Removed Favicon.ico Bad Request

**I ran a test on this website and found it was making 2 requests with one bad request.**

image

**I made the necessary changes and now the overall page speed has increased and the total request counts to 1 with no bad request.**

**I also deployed the new project on netlify and compared it with the previous version of the website and found the following metrics. Have a look**

image

Read full report on Gtmetrix : [Bestmotherfucking.website Report](https://gtmetrix.com/compare/UwN9r4p1/omfWTn91)

So overall the benefits of this pull request is
* Bad request removed
* Page Speed Increased
* Page Size Decreased

### CODE REVIEW

**Comment by KeenRivals** [comment]
Seems kind of hacky, but I've been a bit annoyed by the favicon requests 
for a while. I don't think it really affects browser loads since they 
seem to do it in the background asynchronously. That text looks like the 
start of a PNG header, but what happens if you give it an empty data url?

**Comment by realabbas** [comment]
> Seems kind of hacky, but I've been a bit annoyed by the favicon requests for a while. I don't think it really affects browser loads since they seem to do it in the background asynchronously. That text looks like the start of a PNG header, but what happens if you give it an empty data url?

It does not make the browser interpret the current HTML code as favicon (which would be the case with **href="#" or href=""**

Also, removing the bad requests provides a lot of benefits as mentioned above

**Comment by KeenRivals** [comment]
I meant something like `"data:image/png;base64,"`

**Comment by realabbas** [comment]
> I meant something like `"data:image/png;base64,"`

Yeah, it will work fine. 
I ran a test again and it's working

image

Report: https://gtmetrix.com/reports/dazzling-stonebraker-28ef9c.netlify.com/c8UeD2So

**Comment by realabbas** [comment]
Hey @KeenRivals Review it?

**Pull request closed without merging**
