### PR TITLE
Javascript -> JavaScript

### PR DESCRIPTION
**Pull request by bryndyment**
(https://en.wikipedia.org/wiki/JavaScript)

There, i made it better!

### CODE REVIEW

**Comment by jennydaman** [comment]
You mean EMCAScript?

**Comment by bryndyment** [comment]
no, it's just that it's spelled "JavaScript", not "Javascript" …

**Comment by jennydaman** [comment]
I was just poking fun at your nit-picking dw about it

**Comment by bryndyment** [comment]
@jennydaman got it!  (but i think you mean E**CM**AScript ;)

**Comment by KeenRivals** [comment]
Pedantry I can get behind. Thank you!

**Pull request merged**
